<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\tModLoader.targets" />
  <PropertyGroup>
    <AssemblyName>CalamityRuTranslate</AssemblyName>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="CalamityMod">
      <HintPath>..\ModAssemblies\CalamityMod_v2.1.1.dll</HintPath>
    </Reference>
    <Reference Include="CatalystMod">
      <HintPath>..\ModAssemblies\CatalystMod_v1.1.2.3.dll</HintPath>
    </Reference>
    <Reference Include="Fargowiltas">
      <HintPath>..\ModAssemblies\Fargowiltas_v3.3.6.dll</HintPath>
    </Reference>
    <Reference Include="FargowiltasSouls">
      <HintPath>..\ModAssemblies\FargowiltasSouls_v1.7.2.dll</HintPath>
    </Reference>
    <Reference Include="InfernumMode">
      <HintPath>..\ModAssemblies\InfernumMode_v2.0.1.27.dll</HintPath>
    </Reference>
    <Reference Include="NoxusBoss">
      <HintPath>..\ModAssemblies\NoxusBoss_v1.2.27.dll</HintPath>
    </Reference>
    <Reference Include="PathOfTerraria">
      <HintPath>..\ModAssemblies\PathOfTerraria_v0.3.4.dll</HintPath>
    </Reference>
    <Reference Include="Redemption">
      <HintPath>..\ModAssemblies\Redemption_v0.8.0.4100.dll</HintPath>
    </Reference>
    <Reference Include="SpiritMod">
      <HintPath>..\ModAssemblies\SpiritMod_v1.5.0.38.dll</HintPath>
    </Reference>
    <Reference Include="StarsAbove">
      <HintPath>..\ModAssemblies\StarsAbove_v2.1.5.1.dll</HintPath>
    </Reference>
    <Reference Include="ThoriumMod">
      <HintPath>..\ModAssemblies\ThoriumMod_v1.7.2.5.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>